id: opecha:P007910
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137806
  title: བྱིས་པའི་གཙུག་ལག་འབྲུ་གསུམ་པ། ༼རྒྱ་བོད་ཤན་སྦྱར།༽
  volume:
    d049804e138a43e88ed44ba590ed5f40:
      image_group_id: I2PD18853
      title: Volume 1 of byis pa'i gtsug lag 'bru gsum pa/
      volume_number: 1
      total_pages: 48
  author: ''
ebook_metadata:
  title: བྱིས་པའི་གཙུག་ལག་འབྲུ་གསུམ་པ། ༼རྒྱ་བོད་ཤན་སྦྱར།༽
  author: ''
  sku: P007910
  cover: cover.jpg
  layers:
  - pagination
