id: P007910
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:48:41.520214
source_metadata:
  id: bdr:W1PD137806
  title: བྱིས་པའི་གཙུག་ལག་འབྲུ་གསུམ་པ། ༼རྒྱ་བོད་ཤན་སྦྱར།༽
  author: ''
  volumes:
    d049804e138a43e88ed44ba590ed5f40:
      image_group_id: I2PD18853
      title: Volume 1 of byis pa'i gtsug lag 'bru gsum pa/
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
