id: P007910
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137806
  title: བྱིས་པའི་གཙུག་ལག་འབྲུ་གསུམ་པ། ༼རྒྱ་བོད་ཤན་སྦྱར།༽
  author: ''
  volumes:
    90fb141886584729b7f9e7c052e37714:
      image_group_id: I2PD18853
      title: ''
      volume_number: 1
      total_pages: 48
ebook_metadata:
  title: བྱིས་པའི་གཙུག་ལག་འབྲུ་གསུམ་པ། ༼རྒྱ་བོད་ཤན་སྦྱར།༽
  author: ''
  sku: P007910
  cover: cover.jpg
  layers:
  - pagination
